name: Publish Library to npm

on:
  push:
    tags:
      - 'crezco-donation-app@v*'  # Detectará tags en el formato crezco-donation-app@vX.Y.Z
      - 'crezco-donation-paypal@v*'  # Para futuras librerías
      - 'crezco-donation-cashapp@v*'  # Para futuras librerías

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Extract Library and Version
        id: extract
        run: |
          TAG_NAME=${{ github.ref_name }}
          LIBRARY=$(echo $TAG_NAME | cut -d'@' -f1)
          VERSION=$(echo $TAG_NAME | cut -d'@' -f2)
          echo "LIBRARY=$LIBRARY" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Library: $LIBRARY"
          echo "Version: $VERSION"

      - name: Install Root Dependencies
        run: npm ci

      - name: Install Library Dependencies
        working-directory: projects/${{ env.LIBRARY }}
        run: npm ci

      - name: Build Library
        run: npx ng build ${{ env.LIBRARY }} --configuration=production

      - name: Publish to npm
        working-directory: dist/${{ env.LIBRARY }}
        run: npm publish --access public
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh release create ${{ github.ref }} \
              --title "Release ${{ env.LIBRARY }} v${{ env.VERSION }}" \
              --notes "🚀 Nueva versión `${{ env.LIBRARY }}@${{ env.VERSION }}` publicada en npm."
